### ISSUE TITLE
SENECA TERMINATED at 2017-03-30T03:28:18.079Z. See above for error report

### ISSUE THREAD

**Issue by campanagerald** [senecajs/seneca#617]
We are using seneca for our backend services. My problem is seneca terminate when I respond an error. I am using express.

here is the code who called the service:

this.add('role:signupAPI,path:signup', (msg, respond) => {
        let prospect = msg.args.body;
        this.act('role:signup', {
            cmd: 'save',
            fatal$: false,
            message: prospect,
        }, respond);
    });

    // :/signup
    this.add('init:signupAPI', (msg, respond) => {
        this.act('role:web', {routes: {
            pin: 'role:signupAPI,path:*',
            map: {
                signup: { POST:true }
            }
        }}, respond);
    });

Here is the code that will respond an error

this.add('role:signup, cmd:save', (msg, respond) => {
        return bluebird.coroutine(function* (){
            let prospect = msg.message;

            // check if email is already exist
            var isEmailExists = yield signupTransaction.isEmailExist(prospect.email);
            
            if(isEmailExists) {
                return respond(new Error('Email existed'));       
            }
            
        })();
    });

Here is the error:

Seneca Fatal Error

Message: seneca: Action cmd:save,role:signup failed: Email existed.

Code: act_execute

Details: { message: 'Email existed',
  pattern: 'cmd:save,role:signup',
  instance: 'Seneca/nfrnhmrey6kk/1490844487208/5168/3.3.0/-',
  'orig$': {},
  'message$': 'Email existed',
  plugin: {} }
.
.
.
.

Code\\CachedData',  VSCODE_PID: '5208',  VSCODE_SHARED_IPC_HOOK: '\\\\.\\pipe\\code-4c46c1-1.10.2-shared-sock',  windir: 'C:\\
Windows' }

SENECA TERMINATED at 2017-03-30T03:28:18.079Z. See above for error report.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! philyes-api@1.0.0 start: `node build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the philyes-api@1.0.0 start script 'node build/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the philyes-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs philyes-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls philyes-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MangoSoft\Documents\sources\philyes-api\npm-debug.log

Please help.

**Comment by Pulankit-so** [comment]
@campanagerald @rjrodger Facing same issue when using seneca-mesh can't set fatal$ to false it is always true for plugins.Check this peace of code in lib/plugin.js line 235 



      function make_delegate (instance, plugin) {
          
      // Adjust Seneca API to be plugin specific.
        
    var delegate = instance.delegate({
             plugin$: {
               name: plugin.name,
               tag: plugin.tag
            },
           // Act calls inside the plugin definition function are not gated.
           // ungate$: true,
           fatal$: true
     })

it seems that when act is called using seneca-mesh plugin, the service always terminates the process on any error returned.Also,Not sure if there is need of terminating the process by seneca even in case of fatal errors, i as it gives no option for the developers to handle fatal error on their end, like for my use case i want to run two `seneca` instance and hence two services as part of one process. if any internal error(fatal) occurs in one of the service i would rather want to catch that error and close that particular seneca instead of terminating the complete process.

**Comment by StarpTech** [comment]
@Pulankit-so @campanagerald seneca seperate errors in two categorys

- fatal errors
- business errors

if you pass an error as first argument this is a fatal error and wil crash your process. Use PM2 or similiar to restart your process.
You have to pass you error in the response payload to transfer business errors. This convention is ugly. There is a big issue around error handling. https://github.com/senecajs/seneca/issues/398 but no activity since years.

**Comment by Pulankit-so** [comment]
@StarpTech  Thanks for the info but still wanted to make this process termination thing optional as setting seneca.fixedargs,fatal$ to false  does not work with seneca-mesh.

**Comment by StarpTech** [comment]
@Pulankit-so sry but I never tried to make this working because its bad practice. Your process should be restarted in a clear state.

**Comment by Pulankit-so** [comment]
@StarpTech  ohk thanks i just wanted to analyse the stats for my services and create a gracefull shutdown mechanism in case of fatal errors so that other services are not affected and server responds with a internal serval error instead of server crashing .

**Comment by StarpTech** [comment]
@Pulankit-so Im the wrong person for that I dont use seneca anymore.

**Comment by rjrodger** [comment]
@Pulankit-so that bug is fixed in the latest version of seneca-mesh

Also, don't use `=>` to define message actions, you won't get the right Seneca instance, as `this` will be from the parent context

**Comment by Pulankit-so** [comment]
@rjrodger it still crashes,( seneca-mesh v0.10.0) when a service say `A`, tries to call service `B`  and if there is some error thrown on B due to that particular call, then service B  crashes immediately and terminates the process, Hence does not shut down gracefully. When i call the service B from service B itself i.e using same seneca it works fine.
